### ISSUE TITLE
Formatting of prices adds in a comma, when re-saved everything after the comma is removed

### ISSUE THREAD

**Issue by deanfields** [KuriousAgency/commerce-currency-prices#1]
If you enter a price such 9999 into one of the currency fields and save it, they are reformatted to 9,999 when viewing the product edit page.

When you save the product again, it removes everything after the comma so the price becomes 9.

**Comment by mikeymeister** [comment]
@deanfields Thanks for reporting this. The latest release (2.3.8) should fix this issue.
