### ISSUE TITLE
Plugin with bulk-pricing is causing problems with the cost  

### ISSUE THREAD

**Issue by dgtlcrftrs** [KuriousAgency/commerce-currency-prices#11]
When this plugin is enabled it causes the bulk pricing to not be set correctly but disabling sets the correct price

**Comment by mcjackson18** [comment]
Hi @dgtlcrftrs this could be due to the order your plugins are installed. Please can you try uninstalling both currency prices and bulk pricing and then installing currency prices first and bulk pricing after.

**Comment by dgtlcrftrs** [comment]
@mcjackson18 Hi I have given this a try, and it didn't seem to do anything

**Comment by dgtlcrftrs** [comment]
@mcjackson18 I have tried completely remove these items and reinstalling them in the order suggested with no luck too. 

I guess the currency pricing plugin needs to check if bulk-pricing is installed and if there is a field associated on the product which has a price  that can be applied to the product.

Maybe instead of calling the same event in each plugin, (not ever tried it) but have a shared module that gets installed (like the way sprout suite does) which gets attached to the line item event. In that method, you could check if each of the plugins are installed, and if the product has any bulk fields that should apply instead of the currency one before calling the methods from each plugin that modifies the price? _Just an idea off the top of my head_

**Comment by mcjackson18** [comment]
@dgtlcrftrs, I've tested again with both plugins (Bulk Pricing & Currency Prices) installed but can't replicate the issue. 

Can I check, on your Bulking Pricing field do you have the option to enter a price for each payment currency you have setup:

![Screenshot 2020-02-21 at 14 06 41](https://user-images.githubusercontent.com/39083512/75041314-3e0b5d00-54b4-11ea-8f15-bc726d9383ac.png)

**Comment by dgtlcrftrs** [comment]
Yes I can set the prices on the bulk for each currency setup. I am also using it with 0 units and with a specific group if that at all helps with the testing

**Comment by dgtlcrftrs** [comment]
It\s certainly running out of order because it puts the 'original price' as the bulk price in the backend and the currency price as the sale price.

**Comment by mcjackson18** [comment]
The bulk pricing is being ignored when using 0 units. Please can you try changing the 0 unit qty to 1, going to a product and entering a 1 unit price for each currency.

**Comment by dgtlcrftrs** [comment]
Actually sorry made a mistake it does already seem to be set to 1, but I'll go back and re-save it with 1 and see if that makes a difference.

**Comment by mcjackson18** [comment]
@dgtlcrftrs the bulk pricing plugin was updated earlier this month, please can you test using the latest version to see if this resolves this issue.

**Comment by dgtlcrftrs** [comment]
@mcjackson18 I believe this is now working after doing the update
