### ISSUE TITLE
Error when adding discount base price containing thousand seperator 

### ISSUE THREAD

**Issue by anchovy** [KuriousAgency/commerce-currency-prices#14]
### Description
Related to #5 
Commerce products/variants allow a price to be entered with a thousand separator.
In our case we have:
NZD: 59.95
YPN: 3,845 (entering 3845, on save is displayed as 3,845).

We've got a 2 for one offer. if I copy the YPN amount from the product and add as the discount amount to a promotion Base amount it throw the error....

> A non well formed numeric value encountered in .../vendor/kuriousagency/commerce-currency-prices/src/services/DiscountsService.phpat line 112
```
$record = DiscountsPricesRecord::findOne(['discountId'=>$id, 'paymentCurrencyIso'=>$key]);
 
            if (!$record) {
                $record = new DiscountsPricesRecord();
            }
 
            $record->discountId = $id;
            $record->paymentCurrencyIso = $key;
            foreach ($this->_fields as $field) {
                $record->$field = $value[$field] * -1;
            }
            $record->save();
        }
    }
}
```

### Steps to reproduce

1. create a promotion and add a value that contains a comma. i.e. 3,845

### Additional info

- Craft version: Craft Pro 3.3.17
- PHP version: 7.2.14
- Database driver & version: MySQL 5.7.22
- Plugins & versions:
Commerce Currency Prices | 2.6.3
Craft Commerce | 2.2.8

**Comment by mcjackson18** [comment]
@anchovy this has now been fixed in version 2.7
