### ISSUE TITLE
Plugin has started throwing deprecation error.

### ISSUE THREAD

**Issue by adampatpattison** [KuriousAgency/commerce-currency-prices#15]
Since updating Craft Commerce to  version 3.1.3 the plugin has started throwing the following deprecation error:

Deprecation error: The setting of “saleAmount” has been deprecated. “saleAmount” is automatically calculated.

Stack Trace:

24 | Deprecation error: The setting of “saleAmount” has been deprecated. “saleAmount” is automatically calculated.Called from /var/www/html/vendor/craftcms/commerce/src/models/LineItem.php:374
-- | --
23 | craft\commerce\models\LineItem::setSaleAmount(0)Called from /var/www/html/vendor/yiisoft/yii2/base/Component.php:180
22 | craft\commerce\models\LineItem::__set("saleAmount", 0)Called from /var/www/html/vendor/kuriousagency/commerce-currency-prices/src/CurrencyPrices.php:345
21 | kuriousagency\commerce\currencyprices\CurrencyPrices::kuriousagency\commerce\currencyprices\{closure}(craft\commerce\events\LineItemEvent)
20 | call_user_func(Closure, craft\commerce\events\LineItemEvent)Called from /var/www/html/vendor/yiisoft/yii2/base/Event.php:312
19 | yii\base\Event::trigger("craft\commerce\services\LineItems", "populateLineItem", craft\commerce\events\LineItemEvent)Called from /var/www/html/vendor/yiisoft/yii2/base/Component.php:636
18 | craft\commerce\services\LineItems::trigger("populateLineItem", craft\commerce\events\LineItemEvent)Called from /var/www/html/vendor/craftcms/commerce/src/models/LineItem.php:643
17 | craft\commerce\models\LineItem::populateFromPurchasable(craft\commerce\elements\Variant)Called from /var/www/html/vendor/craftcms/commerce/src/models/LineItem.php:567
16 | craft\commerce\models\LineItem::refreshFromPurchasable()Called from /var/www/html/vendor/craftcms/commerce/src/elements/Order.php:1513
15 | craft\commerce\elements\Order::recalculate()Called from /var/www/html/vendor/craftcms/commerce/src/elements/Order.php:1605
14 | craft\commerce\elements\Order::afterSave(false)Called from /var/www/html/vendor/craftcms/cms/src/services/Elements.php:2125
13 | craft\services\Elements::_saveElementInternal(craft\commerce\elements\Order, false, false, true)Called from /var/www/html/vendor/craftcms/cms/src/services/Elements.php:531
12 | craft\services\Elements::saveElement(craft\commerce\elements\Order, false)Called from /var/www/html/vendor/craftcms/commerce/src/controllers/CartController.php:343
11 | craft\commerce\controllers\CartController::_returnCart()Called from /var/www/html/vendor/craftcms/commerce/src/controllers/CartController.php:246
10 | craft\commerce\controllers\CartController::actionUpdateCart()
9 | call_user_func_array([craft\commerce\controllers\CartController, "actionUpdateCart"], [])Called from /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php:57
8 | yii\base\InlineAction::runWithParams(["p" => "/shop/checkout/addresses"])Called from /var/www/html/vendor/yiisoft/yii2/base/Controller.php:157
7 | craft\commerce\controllers\CartController::runAction("update-cart", ["p" => "/shop/checkout/addresses"])Called from /var/www/html/vendor/craftcms/cms/src/web/Controller.php:178
6 | craft\commerce\controllers\CartController::runAction("update-cart", ["p" => "/shop/checkout/addresses"])Called from /var/www/html/vendor/yiisoft/yii2/base/Module.php:528
5 | craft\web\Application::runAction("commerce/cart/update-cart", ["p" => "/shop/checkout/addresses"])Called from /var/www/html/vendor/craftcms/cms/src/web/Application.php:291
4 | craft\web\Application::runAction("commerce/cart/update-cart", ["p" => "/shop/checkout/addresses"])Called from /var/www/html/vendor/craftcms/cms/src/web/Application.php:559
3 | craft\web\Application::_processActionRequest(craft\web\Request)Called from /var/www/html/vendor/craftcms/cms/src/web/Application.php:270
2 | craft\web\Application::handleRequest(craft\web\Request)Called from /var/www/html/vendor/yiisoft/yii2/base/Application.php:386
1 | craft\web\Application::run()Called from /var/www/html/web/index.php:42

**Comment by PieterxJan** [comment]
We've got the same error. Is there any progress on this?

**Comment by mcjackson18** [comment]
@adampatpattison, @PieterxJan this has now been fixed in version 2.7.
