### ISSUE TITLE
Error when duplicating a product from the product page itself

### ISSUE THREAD

**Issue by deanfields** [KuriousAgency/commerce-currency-prices#16]
HTTP 500 – Internal Server Error – yii\web\ServerErrorHttpException
An error occurred when duplicating the product.

Undefined offset: 0
in /var/www/html/vendor/kuriousagency/commerce-currency-prices/src/CurrencyPrices.php at line 248

This isn't happening when duplicating from the product list page.

**Comment by mcjackson18** [comment]
@deanfields, this has been fixed in 2.7.1
