### ISSUE TITLE
Wrong payment currencies in orders

### ISSUE THREAD

**Issue by palomamtnez** [KuriousAgency/commerce-currency-prices#17]
**Description**
I have set up multiple payment currencies for craft commerce:
NZD - which is the base currency, AUD, EUR, GBP, JPY, USD.

When I go to Commerce -> Orders -> All orders, the total price of the order is rendered as expected in the grid as shown in the picture:
![Screen Shot 2020-11-25 at 9 15 50 AM](https://user-images.githubusercontent.com/13962572/100274716-cd095080-2fc3-11eb-8818-b46adb1adacc.png)

But when I click on the order, the order summary always shows in NZD even if it was paid for in another currency:
![Screen Shot 2020-11-25 at 9 10 12 AM](https://user-images.githubusercontent.com/13962572/100274753-dabed600-2fc3-11eb-9508-70082673fb2d.png)

I'm not sure if this is a bug or I am missing something.

**Expected behavior**
To have the order summary in the currency the order was paid in.

**Additional info**

- Craft version: Pro 3.5.14
- PHP version: 7.3.19
- Database driver & version: MySQL 5.6.48
- Other Plugins & versions:

Abandoned Cart for Craft Commerce 1.5.3
Asset Rev 6.0.2
Cloudflare 0.5.1
Colorit 1.0.9.3
Commerce Currency Prices 2.6.4
Craft Commerce 3.1.9
Element API 2.6.0
Embedded Assets 2.2.6
Facebook Product Catalog 1.2.0
Freeform 3.6.12
Google Shopping Feed 1.2.1
Imager v2.4.0
Image Resizer 2.0.9
Instant Analytics 1.1.7
HTTP2 Server Push 1.0.1
Mailgun 1.4.3
Matrix Toolbar 1.0.6
Navigation 1.3.20
Neo 2.7.19
PayPal for Craft Commerce 2.1.0.1
Redactor 2.6.1
Retour 3.1.39
SEO 3.3.8
Stripe for Craft Commerce 2.3.1.1
Typed link field 1.0.23

**Comment by mcjackson18** [comment]
@palomamtnez, I'm going to close this ticket for now as this looks like a bug in commerce - https://github.com/craftcms/commerce/issues/1890
