### ISSUE TITLE
Error when adding new variants due to price formatting

### ISSUE THREAD

**Issue by dgtlcrftrs** [KuriousAgency/commerce-currency-prices#5]
When adding new variants to a product, if the prices are formatted with a comma it will error saving the product.

i.e 1,000 is set in the product field prices if adding a new variant and setting prices on the new variants, it will error if any of the variants (including previously added ones) have a comma in the pricing formatting. Saving the product and adding other attributes such as weight doesn't cause the error. Only seemed to be when adding new variants and setting pricing at that point

**Comment by samuelbirch** [comment]
thanks, we'll take a look.

**Comment by samuelbirch** [comment]
I can't seem to replicate the error, 
please can you say what version of commerce and commerce-prices that you are using?

**Comment by mcjackson18** [comment]
@dgtlcrftrs, this has now been fixed in version 2.7
