### ISSUE TITLE
bug in shipping conditions, not getting shipping method

### ISSUE THREAD

**Issue by boldenamsterdam** [KuriousAgency/commerce-currency-prices#7]
Looks like we are dealing with a bug.

I'm not getting a shipping method for my current selected currency, but I'm above the minimum total order price of this currency and below the max total weight. It looks like it is now being validated on the currency with the highest total order price.

How to reproduce:

I have 3 currencies: 
1. Dollar
2. Euro
3. Pound Sterling

**My shipping condition is:** 
_Minimum cart total order price_
1. Dollar - $45
2. Euro - €40
3. Pound - £40

_Max weight_

1. 20 Kilograms

When I put a product in my cart with a value of £42 Pound I'm **not** getting a shipping method. When I add another product so my total cart amount is going to £46 Pound I'm now seeing a shipping method.
So the highest amount in the wrong currency is causing the bug.

CraftCMS: **3.2.9**
Commerce: **2.1.11**
Commerce Currency Prices: **>= 2.4.2**

**Comment by boldenamsterdam** [comment]
> It looks like it is now being validated on the currency with the highest total order price.

The above quote is not correct.
Found out it is being validated on the default currency, which is dollar in our case and also the highest total order price.

**Comment by mcjackson18** [comment]
Hi @boldenamsterdam, leave this with us and we'll investigate as soon as we can.

**Comment by mcjackson18** [comment]
@boldenamsterdam this is fixed in 2.5.2

**Comment by boldenamsterdam** [comment]
Hi @mcjackson18 ,

We haven't really been able to test the new versions.
Because since the updates we are not able to see the shipping cost fields in all the currencies we have set.

I expected to see 3 fields: USD, EUR, Pound

![Screenshot 2019-10-31 at 14 06 32](https://user-images.githubusercontent.com/7466604/67949759-95757c80-fbe8-11e9-9063-1e04962757be.png)

I do get an JS error in the console, maybe it's related to this.

![Screenshot 2019-10-31 at 14 12 51](https://user-images.githubusercontent.com/7466604/67949776-a0301180-fbe8-11e9-88ba-28c7727a7fbd.png)

**Comment by mcjackson18** [comment]
@boldenamsterdam this is now fixed in 2.5.5

**Comment by boldenamsterdam** [comment]
Hi @mcjackson18 

Unfortunately we cannot get it to work, we've sent a screencast to your agency e-mail address.

**Comment by mcjackson18** [comment]
Hi @boldenamsterdam, we've not received an email from you, please can you try sending the screencast again to support at kurious dot agency.
