### ISSUE TITLE
Calling unknown method when adding products to cart

### ISSUE THREAD

**Issue by cjgrauco** [KuriousAgency/commerce-currency-prices#9]
Im using the commerce standard shop templates to try your plugin. when i add an item to the cart i get a error:

Unknown Method – yii\base\UnknownMethodException
Calling unknown method: kuriousagency\commerce\currencyprices\services\CurrencyPricesService::getPricesByShippingRuleIdAndCurrency()

The function is being called from the Shipping adjuster on line 77 and 94, but it's using the wrong service. The getPricesByShippingRuleIdAndCurrency function is placed in the Shipping service, not the CurrencyPrices one.

**Comment by mcjackson18** [comment]
@cjgrauco this is now fixed in 2.5.3

**Comment by cjgrauco** [comment]
Perfect, thanks a lot!
